# docs.serverless.com
service: pl-identity-manage
disabledDeprecations:
  # To disable specific deprecation with code "CODE_1"
  - CODE_1
  # To disable all deprecation messages
  - '*'
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
plugins:
  #Add the plugins to your serverless.yml file and make sure that serverless-plugin-typescript precedes serverless-offline as the order is important:
  - serverless-plugin-typescript
  - serverless-offline
package:
  excludeDevDependencies: true
functions:
  signupUser:
    handler: src/drivers/lambda/SignupUser.handler
    events:
      - http:
          path: identity-manage/users/signup
          method: post
          cors: true
  loginUser:
    handler: src/drivers/lambda/LoginUser.handler
    events:
      - http:
          path: identity-manage/users/login
          method: post
          cors: true
  logoutUser:
    handler: src/drivers/lambda/LogoutUser.handler
    events:
      - http:
          path: identity-manage/users/logout
          method: post
          cors: true
  changePasswordUser:
    handler: src/drivers/lambda/ChangePassword.handler
    events:
      - http:
          path: identity-manage/users/change-password
          method: put
          cors: true
  forgotPassword:
    handler: src/drivers/lambda/ForgotPassword.handler
    events:
      - http:
          path: identity-manage/users/forgot-password
          method: post
          cors: true
  confirmPasswrod:
    handler: src/drivers/lambda/ConfirmPassword.handler
    events:
      - http:
          path: identity-manage/users/confirm-password
          method: post
          cors: true
